#!/usr/bin/env python3
"""Generates app/app-dark.css: a dark theme for the signed-in app.

Reads the app stylesheets, keeps only declarations that carry colours, and remaps
them property-aware:
  * text colours that are dark become light (light text, e.g. on buttons, is kept);
  * backgrounds / borders that are light become dark surfaces (dark ones are kept);
  * saturated mid-tones (brand blue, status colours) are kept;
  * shadows are left alone.
Every rule is scoped to html[data-theme="dark"] .vault-app (and the app's modals),
so the public website is unaffected.

Run: python3 scripts/build-dark-theme.py   (from apps/web)
"""
import colorsys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ["app/globals.css", "app/enterprise.css", "app/app-features.css"]
SKIP_SELECTOR = re.compile(r"^(\.public-|\.mk-|\.api-docs|\.marketing|\.center-screen|\.auth-|\.setup-bg|\.unlock-bg|html|body|:root|\*|\.send-page|\.extension-connect)")
SCOPE = 'html[data-theme="dark"] .vault-app'
COLOR = re.compile(r"#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3,4}\b|rgba?\([^)]*\)|\bwhite\b")
TEXT_PROPS = {"color", "fill", "stroke", "caret-color", "-webkit-text-fill-color", "text-decoration-color"}
SKIP_PROPS = {"box-shadow", "text-shadow", "filter", "mask", "-webkit-mask"}


def parse_color(token):
    token = token.strip()
    if token == "white":
        return (255, 255, 255, 1.0)
    if token.startswith("#"):
        h = token[1:]
        if len(h) in (3, 4):
            h = "".join(c * 2 for c in h)
        r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
        a = int(h[6:8], 16) / 255 if len(h) == 8 else 1.0
        return (r, g, b, a)
    parts = [p.strip() for p in re.split(r"[,\s/]+", token[token.index("(") + 1:-1]) if p.strip()]
    r, g, b = (float(p) for p in parts[:3])
    a = parts[3] if len(parts) > 3 else "1"
    a = float(a[:-1]) / 100 if a.endswith("%") else float(a)
    return (r, g, b, a)


def fmt(r, g, b, a):
    r, g, b = (max(0, min(255, round(v))) for v in (r, g, b))
    if a >= 0.999:
        return f"#{r:02x}{g:02x}{b:02x}"
    return f"rgba({r},{g},{b},{round(a, 3)})"


def remap(token, prop):
    r, g, b, a = parse_color(token)
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    is_text = prop in TEXT_PROPS
    if is_text:
        if l >= 0.62:
            return token  # already light text
        new_l = 0.95 - l * 0.6
        s = min(s, 0.75)
    else:
        if l <= 0.45:
            return token  # already a dark surface
        if s > 0.45 and 0.3 < l < 0.78:
            return token  # brand / status colour
        new_l = 0.085 + (1 - l) * 0.95
        if s < 0.2:
            h, s = 0.62, 0.28  # neutral surfaces get a subtle navy tint
        else:
            s = min(s, 0.55)
    nr, ng, nb = colorsys.hls_to_rgb(h, max(0, min(1, new_l)), s)
    return fmt(nr * 255, ng * 255, nb * 255, a)


def convert_decl(decl):
    if ":" not in decl:
        return None
    prop, value = decl.split(":", 1)
    prop = prop.strip().lower()
    if prop.startswith("--") or prop in SKIP_PROPS or not COLOR.search(value):
        return None
    new_value = COLOR.sub(lambda m: remap(m.group(0), prop), value)
    if new_value == value:
        return None
    return f"{prop}:{new_value.strip()}"


def scope(selector):
    selector = selector.strip()
    if not selector or SKIP_SELECTOR.match(selector):
        return None
    if selector.startswith(".vault-app"):
        return f'html[data-theme="dark"] {selector}'
    return f"{SCOPE} {selector}"


def walk(css):
    """Yields (media_prelude or None, selector_text, body) for plain rules."""
    out = []
    i = 0
    n = len(css)

    def rules(block, media):
        pos = 0
        while pos < len(block):
            brace = block.find("{", pos)
            if brace == -1:
                break
            prelude = block[pos:brace].strip()
            depth, end = 1, brace + 1
            while end < len(block) and depth:
                if block[end] == "{":
                    depth += 1
                elif block[end] == "}":
                    depth -= 1
                end += 1
            body = block[brace + 1:end - 1]
            if prelude.startswith("@media"):
                rules(body, prelude)
            elif not prelude.startswith("@"):
                out.append((media, prelude, body))
            pos = end

    rules(re.sub(r"/\*.*?\*/", "", css, flags=re.S), None)
    return out


def main():
    lines = [
        "/* Generated by scripts/build-dark-theme.py — do not edit by hand. */",
        'html[data-theme="dark"] { color-scheme: dark; }',
        'html[data-theme="dark"] body { background: #0a0f1f; }',
        'html[data-theme="dark"] .vault-app { --background:#0a0f1f; --foreground:#e6ebf7; --card:#111a2e; --card-foreground:#e6ebf7; '
        '--popover:#111a2e; --popover-foreground:#e6ebf7; --secondary:#18233f; --secondary-foreground:#b9c8ff; --muted:#141d33; '
        '--muted-foreground:#9aa6c2; --accent:#1a2544; --accent-foreground:#c3d0ff; --border:#243152; --input:#2a385c; '
        'background: var(--background); color: var(--foreground); }',
    ]
    for source in SOURCES:
        css = (ROOT / source).read_text()
        by_media = {}
        for media, prelude, body in walk(css):
            selectors = [s for s in (scope(part) for part in prelude.split(",")) if s]
            if not selectors:
                continue
            decls = [d for d in (convert_decl(part) for part in body.split(";")) if d]
            if not decls:
                continue
            by_media.setdefault(media, []).append(f"{','.join(selectors)}{{{';'.join(decls)}}}")
        lines.append(f"/* from {source} */")
        for media, rules in by_media.items():
            if media:
                lines.append(f"{media}{{{''.join(rules)}}}")
            else:
                lines.extend(rules)
    (ROOT / "app/app-dark.css").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
