import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import releases from "@/lib/client-releases.json";
import { InstallAction } from "@/components/app-install";

export const metadata: Metadata = { title: "Download Passkey-X for your devices", description: "Download Passkey-X for Windows, macOS and Linux. Get Android autofill, a focused desktop workspace and website save prompts in Chrome and Edge." };

const desktop = [
  { name: "Windows", file: "windows-x64.exe", details: "Windows 10 or later · Intel / AMD 64-bit", install: "Run the installer, then open Passkey-X from Start. The installer can download Microsoft WebView2 when needed.", signing: "Unsigned preview installer" },
  { name: "macOS", file: "macos-universal.dmg", details: "macOS 12 or later · Apple silicon & Intel", install: "Open the disk image and drag Passkey-X into Applications. Launch it from Applications or the Dock.", signing: "Ad-hoc signed preview · Not notarized" },
  { name: "Linux", file: "linux-x64.deb", details: "Ubuntu 24.04-compatible · 64-bit DEB", install: "Open the DEB in your software installer, install its dependencies, then launch Passkey-X from your app menu.", signing: "Unsigned preview package" },
];

// Desktop 1.0 is the self-contained app (bundled vault, browser sign-in, biometric unlock).
const desktopV1 = Number(releases.desktop.split(".")[0]) >= 1;

export default function DownloadPage() {
  return <main className="clients-page">
    <header className="clients-header"><Link href="/" aria-label="Passkey-X home"><Image src="/brand/passkey-x-horizontal.png" alt="Passkey-X by Vlightsoft" width={190} height={48} priority /></Link><Link href="/login">Open web vault ↗</Link></header>
    <section className="clients-hero"><span className="public-kicker">Your vault, within reach</span><h1>Make yourself<br />at home. Everywhere.</h1><p>Your encrypted vault on your computer. A helpful save prompt in your browser. Different tools for different moments. One encrypted vault across your devices.</p><nav className="clients-quick-links" aria-label="Choose your app"><a className="client-primary" href="#desktop">Get the desktop app</a><a className="client-secondary" href="#browser">Get the browser extension</a><a className="client-secondary" href="#android">Get the Android app</a><a className="client-secondary" href="#install-steps">iPhone &amp; web app</a></nav></section>

    <section id="desktop" className="clients-section" aria-labelledby="desktop-heading">
      {desktopV1 ? <div className="clients-section-heading"><span className="client-tag">Desktop app · {releases.desktop}</span><h2 id="desktop-heading">Your vault, built into your computer.</h2><p>Unlock with Windows Hello or Touch ID. Press {"Ctrl/Cmd+Shift+Space"} over any app to find a login and copy it. Copied passwords are hidden from clipboard history and wiped after 30 seconds, screenshots and screen sharing show a blank window, and the vault locks when your computer sleeps or the screen locks. The app is self-contained: it never loads code from a website.</p></div>
        : <div className="clients-section-heading"><span className="client-tag">Desktop app · {releases.desktop} preview</span><h2 id="desktop-heading">Your desktop. A faster workflow.</h2><p>Open directly to sign-in or vault unlock. Find favorites with quick search, and jump to your everyday logins with keyboard shortcuts. Keep quick access in a compact window, reopen it from the system tray, or expand into your full vault, workspaces, sharing and account settings. An internet connection is required.</p></div>}
      <div className="client-grid client-desktop-grid">{desktop.map(platform => {
        const url = `/downloads/desktop/${releases.desktop}/passkey-x-desktop-${releases.desktop}-${platform.file}`;
        return <article className="client-card" key={platform.name}><span className="client-tag">{platform.name}</span><h3>Passkey-X for {platform.name}</h3><p className="client-platform">{platform.details}</p><p>{platform.install}</p><a className="client-primary" href={url} download>Download for {platform.name}</a><a className="client-checksum" href={`${url}.sha256`} download>SHA-256 checksum for {platform.name}</a><span className="client-caption">{platform.signing}</span></article>;
      })}</div>
      {desktopV1 ? <div className="client-release-note"><p><strong>Sign in with your browser.</strong> The app opens passkey-x.com in your browser, where your passkeys, company sign-in and security checks work. Approve the app there and you&apos;re back in seconds. Your vault password is only typed into the app.</p><p><strong>Where fingerprint unlock works.</strong> Windows Hello on Windows 10/11 and Touch ID on Macs with it. Linux uses your vault password and keeps your session in the system keyring. Screen-capture blocking works on Windows and macOS.</p><a className="client-checksum" href={`/releases/desktop-${releases.desktop}.json`}>View release checksums and build details</a></div>
        : <div className="client-release-note"><p><strong>Preview installation.</strong> Windows or macOS may block these packages because a verified publisher signature is not yet available. You can use the web vault or installed web app while signed releases are prepared.</p><p><strong>Built around your vault.</strong> Use Ctrl/Cmd+K for quick access, Ctrl/Cmd+Shift+N to add a login, and Ctrl/Cmd+L to lock while the app is focused. Use the app menu to switch between compact and full windows. Closing the window locks and hides it when a system tray is available; choose Quit to exit. Find exports in Downloads. The vault locks when the app loses focus. Web features update on reload; new desktop versions are installed manually. If a passkey or security check cannot complete in the app, choose <strong>Open in browser</strong> from the app menu.</p><a className="client-checksum" href={`/releases/desktop-${releases.desktop}.json`}>View release checksums and build details</a></div>}
    </section>

    <section id="browser" className="clients-section" aria-labelledby="browser-heading"><article className="client-card client-extension client-extension-feature">
      <div><span className="client-tag">Chrome &amp; Edge · 0.3.0 preview</span><h2 id="browser-heading">“Save this login?”<br />Right when you need it.</h2><p>After you submit a login on a compatible website or web app, Passkey-X offers to save it. Choose <strong>Save</strong>, <strong>Not now</strong>, or <strong>Never for this site</strong>. A changed password offers an update to the matching login in your selected workspace.</p><p>Already saved passwords are skipped when the vault is unlocked. If it is locked, unlock to review the pending login. Nothing is saved without your approval.</p><a className="client-primary" href="/downloads/passkey-x-extension-0.3.0-uat.zip" download>Download extension preview</a><a className="client-checksum" href="/downloads/passkey-x-extension-0.3.0-uat.zip.sha256" download>Extension SHA-256 checksum</a></div>
      <div><h3>Set up once. Save as you go.</h3><ol><li>Use Chrome or Edge <strong>127 or later</strong>. Download and extract the package.</li><li>Open <strong>chrome://extensions</strong> or <strong>edge://extensions</strong>, enable <strong>Developer mode</strong>, and choose <strong>Load unpacked</strong>.</li><li>Select the extracted folder, pin Passkey-X, and choose <strong>Connect securely</strong>.</li><li>Sign in to the same account as your desktop or web app. Submit a website login, review the prompt and select a writable workspace to save.</li></ol><p>If the browser does not open the prompt, click the extension’s <strong>SAVE</strong> badge within two minutes. To fill a saved login, open the extension on that website or press <strong>Alt+Shift+X</strong>.</p><span className="client-caption">Unpacked preview · Store release pending · Updating? Replace the extracted files, reload the extension, and reconnect if requested.</span></div>
    </article></section>

    <section id="android" className="clients-section" aria-labelledby="android-heading"><article className="client-card client-extension-feature">
      <div><span className="client-tag">Android app · {releases.android ?? "0.1.0"} preview · Android 9+</span><h2 id="android-heading">Passwords for the apps<br />you use every day.</h2><p>A dedicated mobile home with favorites, recent items and quick actions. Android’s autofill service offers to fill or save a password in compatible native apps after you enable Passkey-X.</p>{releases.android ? <><a className="client-primary" href={`/downloads/android/${releases.android}/passkey-x-android-${releases.android}-preview.apk`} download>Download Android APK</a><a className="client-checksum" href={`/downloads/android/${releases.android}/passkey-x-android-${releases.android}-preview.apk.sha256`} download>Android SHA-256 checksum</a><span className="client-caption">Sideload preview · Temporary signing key · Not on Google Play</span></> : <><p><strong>Native Android download is being prepared.</strong></p><a className="client-primary" href="#install-steps">Install the mobile web app</a><span className="client-caption">System autofill requires the native Android app.</span></>}</div>
      <div><h3>{releases.android ? "Turn on autofill once." : "How the native preview works"}</h3><ol><li>Download the APK on your Android phone and allow your browser to install this app if Android asks.</li><li>Open <strong>Passkey-X Preview</strong>. Sign in directly and unlock your vault.</li><li>Choose <strong>Enable Android autofill</strong> on Home, or <strong>App menu → Autofill settings</strong>. Select Passkey-X in Android Settings.</li><li>In a compatible native app, choose <strong>Unlock Passkey-X to choose a login</strong>. Select a credential, then confirm the app that will receive it.</li><li>When Android offers to save a login, tap <strong>Save</strong>, unlock Passkey-X and confirm the workspace. The login is saved only after that final confirmation.</li></ol><p>Pending logins expire after two minutes. Native apps must expose supported login fields; embedded web forms and browser pages are excluded from this Android preview. Your vault needs an internet connection.</p></div>
    </article><div className="client-release-note"><p><strong>Private on your phone.</strong> Screenshots and recent-app previews are blocked. Leaving the app locks the vault. Imports use Android’s file picker; exports up to 25 MB use the location you choose. Use Open web vault in browser for larger exports or a security check that your Android webview cannot complete.</p><p><strong>Preview updates.</strong> This build uses a temporary signing key. A later preview may require uninstalling the previous app before installation. Keep your vault password and recovery key available; your encrypted account data remains on the service.</p>{releases.android && <a className="client-checksum" href={`/releases/android-${releases.android}.json`}>View Android release details</a>}</div></section>

    <section id="install-steps" className="clients-section" aria-labelledby="mobile-heading"><div className="clients-section-heading"><span className="client-tag">Installed web app</span><h2 id="mobile-heading">A place on your home screen.</h2><p>A lighter option for iPhone, iPad and any supported browser. Launch directly into your account, then use the mobile layout for favorites, search and quick actions.</p><InstallAction /></div><div className="client-grid">
      <article className="client-card"><span className="client-tag">Android</span><h3>Your everyday companion.</h3><p>Install the web app from Chrome for quick access from your home screen.</p><ol><li>Open <strong>passkey-x.com/download</strong> in Chrome.</li><li>Tap <strong>Install Passkey-X</strong> above, or open the ⋮ menu and choose <strong>Add to Home screen → Install</strong>.</li><li>Open Passkey-X, sign in, and unlock your vault.</li></ol><span className="client-caption">Installed web app · Online vault access</span></article>
      <article className="client-card"><span className="client-tag">iPhone &amp; iPad</span><h3>Your vault, one tap away.</h3><p>Use Safari to add Passkey-X to your apps.</p><ol><li>Open <strong>passkey-x.com/download</strong> in Safari.</li><li>Tap <strong>Share → Add to Home Screen</strong>. Keep <strong>Open as Web App</strong> enabled when shown.</li><li>Tap <strong>Add</strong>, then open Passkey-X from the home screen.</li></ol><span className="client-caption">Installed web app · Native iOS autofill is not included</span></article>
    </div><p className="client-release-note">On a computer, Chrome and Edge also offer <strong>Install app</strong>; supported Safari versions offer <strong>Add to Dock</strong>.</p></section>

    <section className="clients-details"><h2>Stay in control.</h2><div><p><strong>Private by design.</strong> Your vault decrypts on your device. Pending logins stay in extension memory for at most two minutes and are cleared when you dismiss, lock, close the tab or move to another origin.</p><p><strong>One account across devices.</strong> Saved changes sync through your encrypted vault. Refresh or reload another client to see them. The web and desktop vaults also lock after five minutes without activity.</p><p><strong>Choose the right companion.</strong> The extension handles websites. Android handles compatible native mobile apps. Desktop focuses on quick search, favorites and keyboard access. System autofill inside other desktop apps and native iOS autofill are not included.</p></div></section>
    <footer className="clients-footer"><span>Passkey-X by Vlightsoft</span><a href="/client-testing.md" download>Combined testing guide</a><Link href="/api-docs">API documentation</Link><Link href="/#security">Security</Link></footer>
  </main>;
}
