import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { InstallAction } from "@/components/app-install";

export const metadata: Metadata = { title: "Download Passkey-X for your devices", description: "Download Passkey-X for Windows, macOS and Linux. Get automatic login save prompts in Chrome and Edge, and install the web app on your phone." };

const desktop = [
  { name: "Windows", file: "windows-x64.exe", details: "Windows 10 or later · Intel / AMD 64-bit", install: "Run the installer, then open Passkey-X from Start. The installer can download Microsoft WebView2 when needed.", signing: "Unsigned preview installer" },
  { name: "macOS", file: "macos-universal.dmg", details: "macOS 12 or later · Apple silicon & Intel", install: "Open the disk image and drag Passkey-X into Applications. Launch it from Applications or the Dock.", signing: "Ad-hoc signed preview · Not notarized" },
  { name: "Linux", file: "linux-x64.deb", details: "Ubuntu 24.04-compatible · 64-bit DEB", install: "Open the DEB in your software installer, install its dependencies, then launch Passkey-X from your app menu.", signing: "Unsigned preview package" },
];

export default function DownloadPage() {
  return <main className="clients-page">
    <header className="clients-header"><Link href="/" aria-label="Passkey-X home"><Image src="/brand/passkey-x-horizontal.png" alt="Passkey-X by Vlightsoft" width={190} height={48} priority /></Link><Link href="/#access">Open web vault ↗</Link></header>
    <section className="clients-hero"><span className="public-kicker">Your vault, within reach</span><h1>Make yourself<br />at home. Everywhere.</h1><p>Your encrypted vault on your computer. A helpful save prompt in your browser. The same account across your devices.</p><nav className="clients-quick-links" aria-label="Choose your app"><a className="client-primary" href="#desktop">Get the desktop app</a><a className="client-secondary" href="#browser">Get the browser extension</a><a className="client-secondary" href="#install-steps">Install on your phone</a></nav></section>

    <section id="desktop" className="clients-section" aria-labelledby="desktop-heading">
      <div className="clients-section-heading"><span className="client-tag">Desktop app · 0.2.0 preview</span><h2 id="desktop-heading">Your vault. Its own window.</h2><p>Access the web vault’s features, including passwords, private notes, workspaces, sharing and account settings. Use the same account and separate vault password. An internet connection is required.</p></div>
      <div className="client-grid client-desktop-grid">{desktop.map(platform => {
        const url = `/downloads/desktop/0.2.0/passkey-x-desktop-0.2.0-${platform.file}`;
        return <article className="client-card" key={platform.name}><span className="client-tag">{platform.name}</span><h3>Passkey-X for {platform.name}</h3><p className="client-platform">{platform.details}</p><p>{platform.install}</p><a className="client-primary" href={url} download>Download for {platform.name}</a><a className="client-checksum" href={`${url}.sha256`} download>SHA-256 checksum for {platform.name}</a><span className="client-caption">{platform.signing}</span></article>;
      })}</div>
      <div className="client-release-note"><p><strong>Preview installation.</strong> Windows or macOS may block these packages because a verified publisher signature is not yet available. You can use the web vault or installed web app while signed releases are prepared.</p><p><strong>Built around your vault.</strong> Lock with Ctrl/Cmd+L, reload with Ctrl/Cmd+R, and find exports in Downloads. The vault locks when the app loses focus. Web features update on reload; new desktop versions are installed manually. If a passkey or security check cannot complete in the app, choose <strong>Open in browser</strong> from the app menu.</p><a className="client-checksum" href="/releases/desktop-0.2.0.json">View release checksums and build details</a></div>
    </section>

    <section id="browser" className="clients-section" aria-labelledby="browser-heading"><article className="client-card client-extension client-extension-feature">
      <div><span className="client-tag">Chrome &amp; Edge · 0.3.0 preview</span><h2 id="browser-heading">“Save this login?”<br />Right when you need it.</h2><p>After you submit a login on a compatible website or web app, Passkey-X offers to save it. Choose <strong>Save</strong>, <strong>Not now</strong>, or <strong>Never for this site</strong>. A changed password offers an update to the matching login in your selected workspace.</p><p>Already saved passwords are skipped when the vault is unlocked. If it is locked, unlock to review the pending login. Nothing is saved without your approval.</p><a className="client-primary" href="/downloads/passkey-x-extension-0.3.0-uat.zip" download>Download extension preview</a><a className="client-checksum" href="/downloads/passkey-x-extension-0.3.0-uat.zip.sha256" download>Extension SHA-256 checksum</a></div>
      <div><h3>Set up once. Save as you go.</h3><ol><li>Use Chrome or Edge <strong>127 or later</strong>. Download and extract the package.</li><li>Open <strong>chrome://extensions</strong> or <strong>edge://extensions</strong>, enable <strong>Developer mode</strong>, and choose <strong>Load unpacked</strong>.</li><li>Select the extracted folder, pin Passkey-X, and choose <strong>Connect securely</strong>.</li><li>Sign in to the same account as your desktop or web app. Submit a website login, review the prompt and select a writable workspace to save.</li></ol><p>If the browser does not open the prompt, click the extension’s <strong>SAVE</strong> badge within two minutes. To fill a saved login, open the extension on that website or press <strong>Alt+Shift+X</strong>.</p><span className="client-caption">Unpacked preview · Store release pending · Updating? Replace the extracted files, reload the extension, and reconnect if requested.</span></div>
    </article></section>

    <section id="install-steps" className="clients-section" aria-labelledby="mobile-heading"><div className="clients-section-heading"><span className="client-tag">Installed web app</span><h2 id="mobile-heading">A place on your home screen.</h2><p>Open your vault from your phone, tablet or browser’s app launcher.</p><InstallAction /></div><div className="client-grid">
      <article className="client-card"><span className="client-tag">Android</span><h3>Your everyday companion.</h3><p>Install the web app from Chrome for quick access from your home screen.</p><ol><li>Open <strong>passkey-x.com/download</strong> in Chrome.</li><li>Tap <strong>Install Passkey-X</strong> above, or open the ⋮ menu and choose <strong>Add to Home screen → Install</strong>.</li><li>Open Passkey-X, sign in, and unlock your vault.</li></ol><span className="client-caption">Installed web app · Online vault access</span></article>
      <article className="client-card"><span className="client-tag">iPhone &amp; iPad</span><h3>Your vault, one tap away.</h3><p>Use Safari to add Passkey-X to your apps.</p><ol><li>Open <strong>passkey-x.com/download</strong> in Safari.</li><li>Tap <strong>Share → Add to Home Screen</strong>. Keep <strong>Open as Web App</strong> enabled when shown.</li><li>Tap <strong>Add</strong>, then open Passkey-X from the home screen.</li></ol><span className="client-caption">Installed web app · iOS and iPadOS</span></article>
    </div><p className="client-release-note">On a computer, Chrome and Edge also offer <strong>Install app</strong>; supported Safari versions offer <strong>Add to Dock</strong>.</p></section>

    <section className="clients-details"><h2>Stay in control.</h2><div><p><strong>Private by design.</strong> Your vault decrypts on your device. Pending logins stay in extension memory for at most two minutes and are cleared when you dismiss, lock, close the tab or move to another origin.</p><p><strong>One account across devices.</strong> Saved changes sync through your encrypted vault. Refresh or reload another client to see them. The web and desktop vaults also lock after five minutes without activity.</p><p><strong>Choose the right companion.</strong> The browser extension handles save prompts and fill on websites and web apps. Password detection and autofill inside other native desktop or mobile apps are not included in this release.</p></div></section>
    <footer className="clients-footer"><span>Passkey-X by Vlightsoft</span><a href="/client-testing.md" download>Combined testing guide</a><Link href="/api-docs">API documentation</Link><Link href="/#security">Security</Link></footer>
  </main>;
}
