import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { InstallAction } from "@/components/app-install";

export const metadata: Metadata = { title: "Get Passkey-X for your devices", description: "Install Passkey-X on Android, iPhone, iPad and desktop, or connect the Chrome and Edge browser extension." };

export default function DownloadPage() {
  return <main className="clients-page">
    <header className="clients-header"><Link href="/" aria-label="Passkey-X home"><Image src="/brand/passkey-x-horizontal.png" alt="Passkey-X by Vlightsoft" width={190} height={48} priority /></Link><Link href="/#access">Open web vault ↗</Link></header>
    <section className="clients-hero"><span className="public-kicker">Your vault, within reach</span><h1>Make yourself<br />at home. Everywhere.</h1><p>Keep your passwords and private information close, with the same encrypted vault on your phone, tablet and computer.</p><InstallAction /></section>
    <section className="client-grid" id="install-steps" aria-label="Installation instructions">
      <article className="client-card"><span className="client-tag">Android</span><h2>Your everyday companion.</h2><p>Install the web app from Chrome for quick access from your home screen.</p><ol><li>Open <strong>passkey-x.com/download</strong> in Chrome.</li><li>Tap <strong>Install Passkey-X</strong> above, or open the ⋮ menu and choose <strong>Add to Home screen → Install</strong>.</li><li>Open Passkey-X, sign in, and unlock your vault.</li></ol><span className="client-caption">Installed web app · Online vault access</span></article>
      <article className="client-card"><span className="client-tag">iPhone &amp; iPad</span><h2>A place on your home screen.</h2><p>Use Safari to add Passkey-X to your apps. Your account and vault password remain separate.</p><ol><li>Open <strong>passkey-x.com/download</strong> in Safari.</li><li>Tap <strong>Share → Add to Home Screen</strong>. Keep <strong>Open as Web App</strong> enabled when shown.</li><li>Tap <strong>Add</strong>, then open Passkey-X from the home screen.</li></ol><span className="client-caption">Installed web app · iOS and iPadOS</span></article>
      <article className="client-card"><span className="client-tag">Windows, macOS &amp; Linux</span><h2>Your vault. Its own window.</h2><p>Install with Chrome or Edge. On supported Macs, Safari also offers Add to Dock.</p><ol><li>Open this page in Chrome or Edge.</li><li>Use <strong>Install Passkey-X</strong> above or the browser’s <strong>Install app</strong> menu.</li><li>Launch Passkey-X from your taskbar, dock or app launcher.</li></ol><span className="client-caption">Installed web app · Automatic update checks</span></article>
      <article className="client-card client-extension"><span className="client-tag">Chrome &amp; Edge · Preview</span><h2>A better way to sign in.</h2><p>Save and fill logins on the exact website you choose. Connect your account securely, then unlock inside the extension.</p><ol><li>Download and extract the extension package.</li><li>Open <strong>chrome://extensions</strong> or <strong>edge://extensions</strong>, enable <strong>Developer mode</strong>, and choose <strong>Load unpacked</strong>.</li><li>Select the extracted folder, pin Passkey-X, and choose <strong>Connect securely</strong>.</li></ol><a className="client-primary" href="/downloads/passkey-x-extension-0.2.0-uat.zip" download>Download extension preview</a><a className="client-checksum" href="/downloads/passkey-x-extension-0.2.0-uat.zip.sha256">SHA-256 checksum</a><span className="client-caption">Preview package · Store release pending</span></article>
    </section>
    <section className="clients-details"><h2>Stay in control.</h2><div><p><strong>Private by design.</strong> Your vault decrypts on your device. Installation does not give the server your vault password or recovery key.</p><p><strong>Lock when you leave.</strong> The app locks when it goes into the background, when the page closes, or after five minutes without activity.</p><p><strong>Know what’s available.</strong> Mobile installation includes the web vault’s features. Filling passwords inside other mobile apps requires a native autofill provider, which is not included in this release.</p></div></section>
    <footer className="clients-footer"><span>Passkey-X by Vlightsoft</span><Link href="/api-docs">API documentation</Link><Link href="/#security">Security</Link></footer>
  </main>;
}
